version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - run:
        name: transpile code
        command: |
          sudo npm install --save-dev webpack webpack-cli
          cd www && mkdir dist && cd ..
          npm run build
      - run:
        name: package build and clean
        command: |
          bash clean.sh
          zip -r spaceshooter.zip www

      - store_artifacts:
          path: spaceshooter.zip
