version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.07.1-node
    steps:
      - checkout
      - run:
         name: install dependecies
         command: |
           java --version
           sudo npm install --save-dev webpack webpack-cli
           sudo npm install -g cordova
      - run:
         name: transpile code
         command: |
           cd www && mkdir dist && cd ..
           npm run build
      - run:
         name: start cordova config
         command: |
           sudo cordova platform add android
           ls
      
      - run:
         name: start apk build
         command: |
           cd platforms
           echo ${ANDROID_HOME}
           echo ${ANDROID_SDK_ROOT}
           export ANDROID_HOME=${ANDROID_HOME}
           export ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}
           sudo cordova build android
           ls -lh android/app/build/outputs/apk/debug/

      - store_artifacts:
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
